### ISSUE TITLE
Simulation Mode - does not move to the next round

### ISSUE THREAD

**Issue by spacechicken** [lmusarella/Pancakeswap-Prediction-Bot#14]
Hi, running the bot is simulation mode to check in Quote strategy  it says BOT STARTED, waiting for next round and then doesnt go to the next round nor record in the history?

**Comment by tankiatwee** [comment]
I initially had this problem until I setup a free endpoint at quicknode.com. When you setup, just ignore the paid add-ons.

Then copy your endpoint 'https://...' and paste for BSC_NODE_PROVIDER_URL in .env file.

**Comment by lmusarella** [comment]
@spacechicken I think its the same problem of  #7, check your BSC_NODE_PROVIDER_URL.

**Comment by spacechicken** [comment]
Yeah signing up for Quick node fixed the issue straight away by replacing the created node with the BSC_NODE_PROVIDER_URL.

I would be greatly interested if you add the martingale strategy to it as well - thanks for your help. Ran each strategy at it is not profitable at the moment but everything works well so its a good base to and better strategies to.

Thanks again!
