### ISSUE TITLE
Martingale 

### ISSUE THREAD

**Issue by domhakke** [lmusarella/Pancakeswap-Prediction-Bot#17]
![Afbeelding van WhatsApp op 2023-06-17 om 17 30 32](https://github.com/lmusarella/Pancakeswap-Prediction-Bot/assets/125758931/7200aa8f-4e09-4b6d-b735-f832c2dafe1e)
It seems like something is going wrong with the Martingale calculation, this simulation runs with $5 bets, and a 2 increment bet amount.
which should end up with a $10 bet.
it seems like this bet amount is not reset in between, because somehow it arrives at a $80 bet, followed by a $160 bet.
this $160 bet results in a profit (won $170 - which isn't accurate because the payout of the round was 2.06)

![image](https://github.com/lmusarella/Pancakeswap-Prediction-Bot/assets/125758931/9e236ed5-be18-4b24-a4dd-50bb51b60fdb)

**Comment by lmusarella** [comment]
Hi, Yes the message Is not so accurate. I have fixed the message. But Is correct, because the 170 Is the 2,06x of the Bet amount of 160.

The bot actually increment every time, there Is no stop. 

In martingale mode the bot reset the Bet amount only when you win.

**Comment by lloydwoods** [comment]
@domhakke curious what your settings are.  That's a good bit of profit.

**Comment by domhakke** [comment]
@lmusarella i see you have made the messages more clear :)
i have updated to the new version, but since then the bot hangs on for me strange moments.
the message it throws is below, i figure this has something to do with information returned by the smart contract.
is it caused by the BSC provider or is it something inside the bot causing this?

i'm only running in simulation mode right now, so don't know if it makes a difference.

/home/ubuntu/bot2/node_modules/@ethersproject/logger/lib/index.js:238
        var error = new Error(message);
                    ^

Error: invalid BigNumber value (argument="value", value=[{"type":"BigNumber","hex":"0x02d852"}], code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (/home/ubuntu/bot2/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/ubuntu/bot2/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/home/ubuntu/bot2/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at BigNumber.from (/home/ubuntu/bot2/node_modules/@ethersproject/bignumber/lib/bignumber.js:239:23)
    at formatFixed (/home/ubuntu/bot2/node_modules/@ethersproject/bignumber/lib/fixednumber.js:43:35)
    at Object.formatUnits (/home/ubuntu/bot2/node_modules/@ethersproject/units/lib/index.js:67:40)
    at formatUnit (/home/ubuntu/bot2/bot-lib/common/utils.module.js:136:34)
    at printTransactionError (/home/ubuntu/bot2/bot-lib/common/print.module.js:212:108)
    at claimRewards (/home/ubuntu/bot2/bot-lib/smart-contracts/pcs-prediction-smart-contract.module.js:138:5)
    at async claimStrategy (/home/ubuntu/bot2/bot-lib/strategies/bet-strategy.module.js:56:16) {
  reason: 'invalid BigNumber value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: [ BigNumber { _hex: '0x02d852', _isBigNumber: true } ]
}

**Comment by lmusarella** [comment]
thanks for reporting, can you give me some more information? what configuration were you using?

**Comment by domhakke** [comment]
Hi,

Configuration wise, it seems to happen in both SIGNAL and QUOTE strategy.
i did not try the others, with a 5 bet, (non reverse / lower quote).
and it happens at random, so there is no real point where the error comes (not near profit or loss goal) not after xx executions it seems completely random.

**Comment by lmusarella** [comment]
seems to happen when he has to claim the win, does it always happen? when you win a round and claim?

**Comment by domhakke** [comment]
No, it doesnt seem to do that on all win claimings.

Van: Luca Musarella ***@***.***>
Verzonden: donderdag 6 juli 2023 17:25
Aan: lmusarella/Pancakeswap-Prediction-Bot ***@***.***>
CC: Dominic Hakke ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [lmusarella/Pancakeswap-Prediction-Bot] Martingale (Issue #17)


seems to happen when he has to claim the win, does it always happen? when you win a round and claim?

**Comment by domhakke** [comment]
Hi,

Indeed happens on claiming a win in the non-simulation.
i tried swapping from quicknode to nodereal, to see if the BSC provider had something to do with it; but it doesnt change it.
I could try to disable autoclaim and see if the issue persists.

**Comment by lmusarella** [comment]
it's probably my regression, tomorrow I'll see if I can fix the problem
right away.

Il gio 6 lug 2023, 22:14 domhakke ***@***.***> ha scritto:

**Comment by lmusarella** [comment]
I should have fixed the error you are getting. It was a special case.

Il ven 7 lug 2023, 00:55 Luca Musarella ***@***.***> ha
scritto:
