### ISSUE TITLE
Bot hangs at Waiting for next round

### ISSUE THREAD

**Issue by lloydwoods** [lmusarella/Pancakeswap-Prediction-Bot#7]
Just found your release and thought I would give it a whirl.  I can launch it via yarn or npm, neither give me errors (oh, BTW, I did have to change the API constants from api.binance.com to data.binance.com as I was getting an error on that) but the bot runs and just sits eternally on "Waiting for next round: XXXXXX".  It displays the correct upcoming round number, and will change if I close the script and re-launch it, but it never progresses past this point.

It is not writing anything to the logs, which I find interesting. 
![image](https://user-images.githubusercontent.com/41762716/227016465-a0de4c0c-a789-4b7a-9135-16432ae9de93.png)

**Comment by lmusarella** [comment]
Hi, thanks for reporting. Why was the Binance API url giving you an error? How long did you wait after the round started? usually after the round opens, you have to wait 1 minute before you see anything displayed.

**Comment by lloydwoods** [comment]
Binance API was saying bad response from server on bot launch.  I'm in the US if that matters, found the other URL via a google search.

Oh yeah, I've waited way more than one minute.  I've ran as my user, ran as root. Let it run for a few hours last night, still just sat at waiting for the next round no matter how long.  Waiting time in the config is still 265000

**Comment by lmusarella** [comment]
I tried changing the binance url. I managed to start the bot correctly, with the default settings, except the simulated mode. Seems to work fine, try to see if the smart contract listeners are being invoked correctly.
![issue_7_test](https://user-images.githubusercontent.com/35798100/227048071-782f910e-cba2-47f1-ad37-51e0a51b544f.PNG)

**Comment by lmusarella** [comment]
To see if smart contract listeners are working. Try inserting console logs and relaunch the bot. I expect the message to be printed. Inside the pcs-bot.js file under EVENTS.START_ROUND_EVENT put a console.log. I made you a screenshot of how to do it.
![issue_7_check](https://user-images.githubusercontent.com/35798100/227049065-7da87ed8-a129-428c-b8c6-46927efe81a1.PNG)

**Comment by lloydwoods** [comment]
Added that code and relaunched.  It still just sits and sits on Waiting for next round.  I don't see any additional log files, and nothing is printing on the screen that wasn't before.

**Comment by lmusarella** [comment]
Interesting, I'll check it out when I get home from work. Have you tried checking that the abi and url of the smart contract are correct?

**Comment by rootisareservedword** [comment]
@lloydwoods Noticed you said you were using the release. I haven't tried the release, but am having mostly success with cloning the repository. @lmusarella has done a fantastic job fixing a couple of issues that I have reported recently, but I'm not sure if the release version has been updated to reflect those changes. You might try just cloning the repo. Btw, thanks for pointing out about how to fix the Binance API errors. I am also getting those errors, so I will try changing the URL. Thanks!

**Comment by lmusarella** [comment]
Unfortunately I can't reproduce your case, however
I released a new release and updated binance urls.

Try re-downloading the project from scratch.

I used https://www.quicknode.com/ to define my node on the BSC chain.

![issue_7_bsc_node](https://user-images.githubusercontent.com/35798100/227340989-5f4248b9-d0cb-4b45-80db-3019739b1457.PNG)

**Comment by lloydwoods** [comment]
Yeah.  I don't know either.   I'm a Linux novice, but I think everything is in order.  It didn't like the newest version of openjs originally, but I managed to install 14.16 which it was happy with.  I cloned again and still no dice.

I was asking where in the code that BSC_NODE_PROVIDER_URL is defined?  Like I found the constant files for the binance price, but I'm not seeing where BSC_NODE_PROVIDER_URL is defined in the code of this script, I was going to try some other URLs for it.

**Comment by domhakke** [comment]
I'm having the same issue as @lloydwoods has, it;s stuck at waiting for next round
i have also added the console.log as indicated above but it's not printing to the console that the smart contract is being triggered.
Im using https://bsc-dataseed1.binance.org/ as the Node url provider?

BSC_NODE_PROVIDER_URL = https://bsc-dataseed1.binance.org

**Comment by lloydwoods** [comment]
> I'm having the same issue as @lloydwoods has, it;s stuck at waiting for next round i have also added the console.log as indicated above but it's not printing to the console that the smart contract is being triggered. Im using https://bsc-dataseed1.binance.org/ as the Node url provider?
> 
> BSC_NODE_PROVIDER_URL = https://bsc-dataseed1.binance.org

Yeah, I know what node URLs to use, but the script calls BSC_NODE_PROVIDER_URL, what other files is that particular constant defined in so I can try a different URL to see if that's my issue?

**Comment by rootisareservedword** [comment]
You mean these? I think you really only need to edit the .env file. I'm using QuickNode and it doesn't hang on the first round.

![image](https://user-images.githubusercontent.com/36577613/227387105-dc856a84-6c14-4297-b016-abe282dbf379.png)

**Comment by lmusarella** [comment]
To modify the variable: BSC_NODE_PROVIDER_URL you need to open the ".env" file.

I recommend using an editor or IDE like VisualStudio. 
Here is the ling for free download https://code.visualstudio.com/download

My node version is 17.1.0

I finally managed to replicate your problem. it is surely the fault of the URL of the node that you have chosen. I copied "https://bsc-dataseed1.binance.org/" in my BSC_NODE_PROVIDER_URL property and here is the result. The same problem.


![issue_7_solved](https://user-images.githubusercontent.com/35798100/227387521-4c2bd10e-63ae-4a9c-8610-6f718ec2dbd0.PNG)

We can see that round 156964 has already started but I didn't get any hits on the console. Your same problem.


![issue_7_solved_1](https://user-images.githubusercontent.com/35798100/227387679-80208875-13f5-423b-8edf-f8f59d129008.PNG)

**Comment by lloydwoods** [comment]
@rootisareservedword  OMG, I didn't even thing about it being in the env file.....that was the issue.

**Comment by lloydwoods** [comment]
@lmusarella You were correct, I built my own node and put that in and it's working perfectly now.  Shoot me your BSC address, this is worthy of a little tip.
